apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e8gnbgbq3-python-gitops
  description: This is GitOps manifest for e8gnbgbq3-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=e8gnbgbq3-python
    backstage.io/kubernetes-id: e8gnbgbq3-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: e8gnbgbq3-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:e8gnbgbq3-python
