apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e8gnbgbq3-python
  janus-idp.io/tekton: e8gnbgbq3-python
  backstage.io/kubernetes-id: e8gnbgbq3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e8gnbgbq3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
